FROM java:openjdk-8-jre-alpine
EXPOSE 8080

RUN apk add --no-cache curl

RUN curl http://192.168.251.222:8081/repository/mvn_repo2/file/store-webapp.jar -o store-webapp.jar
#ENTRYPOINT ["mvn"]
CMD ["java", "-jar", "store-webapp.jar"]
#CMD ls -lrt
