kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: service-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_test_pod
  template:
    metadata:
      labels:
        app: service_test_pod
    spec:
      containers:
      - name: simple-http
        image: 192.168.251.222:8123/repository/sparkdockerrepo/webpod:VERSION
        ports:
        - name: http
          containerPort: 8080
      imagePullSecrets:
      - name: regsecret
